[package]
name = "snitch-detective"
version = "0.0.11"
edition = "2021"
license = "MIT"
description = "Data matcher library used by snitch WASM functions"
categories = ["parser-implementations", "wasm"]
keywords = ["protobuf", "json", "match", "wasm"]
repository = "https://github.com/streamdal/snitch-detective"

[dependencies]
ajson = "0.3.1"
chrono = "0.4.26"
env_logger = "0.10.0"
gjson = "0.8.1"
lazy_static = "1.4.0"
log = "0.4.19"
protobuf = "3.2.0"
protobuf-json-mapping = "3.2.0"
regex = "1.8.4"
snitch-protos = "0.0.14"
thiserror = "1.0.40"
