version: "3"
services:
  snitch-server:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - SNITCH_SERVER_NODE_NAME=node1
      - SNITCH_SERVER_AUTH_TOKEN=1234
      - SNITCH_SERVER_REDIS_URL=redis:6379
      - SNITCH_SERVER_DEBUG=true
    container_name: snitch-server
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - snitch-network

  redis:
    container_name: snitch-redis
    image: redis:latest
    command: redis-server --appendonly yes # This enables AOF persistence
    volumes:
      - redis-data:/data # Persist redis data to this volume
    ports:
      - "6379:6379"
    networks:
      - snitch-network

  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121" # Expose the exporter's port
    networks:
      - snitch-network
    command:
      - '--redis.addr=redis:6379' # Address of the Redis server

  envoy:
    build:
      context: ${PWD}/assets/envoy
      dockerfile: ${PWD}/assets/envoy/Dockerfile
    image: grpcweb/envoy
    container_name: snitch-envoy
    ports:
      - "9091:9091"
      - "9901:9901"
    networks:
      - snitch-network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9191:9090
    restart: unless-stopped
    volumes:
      - ${PWD}/assets/prometheus:/etc/prometheus
      - prom-data:/prometheus
    networks:
      - snitch-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ${PWD}/assets/grafana:/etc/grafana/provisioning/datasources
      - ${PWD}/assets/grafana-data:/var/lib/grafana
    networks:
      - snitch-network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - snitch-network

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
      - ./assets/promtrail/docker-config.yaml:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - snitch-network

volumes:
  redis-data: # Define the volume for redis data
  prom-data:

networks:
  snitch-network:
